language: java

dist: precise

jdk:
        - oraclejdk8

env:
        - SONARHOME=/tmp/sonarqube-5.6.6 SONARAPI=SqApi56
        - SONARHOME=/tmp/sonarqube-6.0   SONARAPI=SqApi56
        - SONARHOME=/tmp/sonarqube-6.1   SONARAPI=SqApi56
        - SONARHOME=/tmp/sonarqube-6.2   SONARAPI=SqApi62
        - SONARHOME=/tmp/sonarqube-6.3.1 SONARAPI=SqApi62
        - SONARHOME=/tmp/sonarqube-6.4   SONARAPI=SqApi62
        - SONARHOME=/tmp/sonarqube-6.5   SONARAPI=SqApi62

matrix:
    fast_finish: true
#    allow_failures:
#        - env: SONARHOME=/tmp/sonarqube-6.5 SONARAPI=SqApi62

# shorten the VM hostname with the new workaround
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
addons:
     hosts:
        - myshorthost
     hostname: myshorthost

before_cache:
        # remove all the artifacts that are installed in local repo because of mvn deploy
        - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube-plugins/cxx
        - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
cache:
    directories:
        - '$HOME/.m2/repository'

before_install:
        - cat /etc/hosts # optionally check the content
        - travis_retry sudo apt-add-repository -y ppa:boost-latest/ppa
        - travis_retry sudo apt-get -qq update
        - travis_retry sudo apt-get -qq install boost1.55

install:
        - cd /tmp
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.6.6.zip
        - unzip -qq sonarqube-5.6.6.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.0.zip
        - unzip -qq sonarqube-6.0.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.1.zip
        - unzip -qq sonarqube-6.1.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.2.zip
        - unzip -qq sonarqube-6.2.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.3.1.zip
        - unzip -qq sonarqube-6.3.1.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.4.zip
        - unzip -qq sonarqube-6.4.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.5.zip
        - unzip -qq sonarqube-6.5.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778.zip
        - unzip -qq sonar-scanner-cli-3.0.3.778.zip
        - cd -

before_script:
        - travis_retry sudo pip install -q requests
        - travis_retry sudo pip install -q behave
        - travis_retry sudo pip install -q colorama

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-scanner-3.0.3.778/bin TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata behave --no-capture --tags=$SONARAPI

after_failure:
        - cat $SONARHOME/logs/sonar.log
        - find . -name "*.log" | xargs cat
