language: java

jdk:
  - oraclejdk7
  - openjdk8


install:
        - cd /tmp
        - wget http://dist.sonar.codehaus.org/sonarqube-4.5.1.zip
        - unzip sonarqube-4.5.1.zip
        - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
        - unzip sonar-runner-dist-2.4.zip
        - cd -

before_script:
        - sudo pip install requests
        - sudo pip install behave
        - sudo pip install colorama

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin SONARHOME=/tmp/sonarqube-4.5.1 behave

