language: java

jdk:
        - oraclejdk8

env:
        - SONARHOME=/tmp/sonarqube-5.6.3
        - SONARHOME=/tmp/sonarqube-6.0
        - SONARHOME=/tmp/sonarqube-6.1
        - SONARHOME=/tmp/sonarqube-6.2-RC2
  
matrix:
    fast_finished: true
    allow_failures:
        - env: SONARHOME=/tmp/sonarqube-6.2-RC2

# shorten the VM hostname with the new workaround
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
addons:
     hosts:
        - myshorthost
     hostname: myshorthost
  
before_install:
        - cat /etc/hosts # optionally check the content
        - travis_retry sudo apt-add-repository -y ppa:boost-latest/ppa
        - travis_retry sudo apt-get -qq update
        - travis_retry sudo apt-get -qq install boost1.55
        
install:
        - cd /tmp
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.6.3.zip
        - unzip -qq sonarqube-5.6.3.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.0.zip
        - unzip -qq sonarqube-6.0.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.1.zip
        - unzip -qq sonarqube-6.1.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.2-RC2.zip
        - unzip -qq sonarqube-6.2-RC2.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.8.zip
        - unzip -qq sonar-scanner-2.8.zip
        - cd -

before_script:
        - travis_retry sudo pip install -q requests
        - travis_retry sudo pip install -q behave
        - travis_retry sudo pip install -q colorama

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-scanner-2.8/bin TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata behave --no-capture
        
after_failure:
        - cat $SONARHOME/logs/sonar.log
        - find . -name "*.log" | xargs cat
