language: java

jdk:
        - oraclejdk8
        - openjdk7

env:
        - SONARHOME=/tmp/sonarqube-4.5.6
#       - SONARHOME=/tmp/sonarqube-5.0.1
        - SONARHOME=/tmp/sonarqube-5.1.2
#       - SONARHOME=/tmp/sonarqube-5.2
        - SONARHOME=/tmp/sonarqube-5.3
        - SONARHOME=/tmp/sonarqube-5.4-RC1
  
matrix:
    fast_finished: true
    allow_failures:
#       - env: SONARHOME=/tmp/sonarqube-5.2
        - env: SONARHOME=/tmp/sonarqube-5.3
        - env: SONARHOME=/tmp/sonarqube-5.4-RC1

before_install:
        - cat /etc/hosts # optionally check the content *before*
        - sudo hostname "$(hostname | cut -c1-63)"
        - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
        - cat /etc/hosts # optionally check the content *after*
        - travis_retry sudo apt-add-repository -y ppa:boost-latest/ppa
        - travis_retry sudo apt-get -qq update
        - travis_retry sudo apt-get -qq install boost1.55
        
install:
        - cd /tmp
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip
        - unzip -qq sonarqube-4.5.6.zip        
#       - travis_retry wget -q http://downloads.sonarsource.com/sonarqube/sonarqube-5.0.1.zip
#       - unzip -qq sonarqube-5.0.1.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.1.2.zip
        - unzip -qq sonarqube-5.1.2.zip        
#       - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.2.zip
#       - unzip -qq sonarqube-5.2.zip   
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.3.zip
        - unzip -qq sonarqube-5.3.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.4-RC1.zip
        - unzip -qq sonarqube-5.4-RC1.zip		
        - travis_retry wget -q http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
        - unzip -qq sonar-runner-dist-2.4.zip
        - cd -

before_script:
        - travis_retry sudo pip install -q requests
        - travis_retry sudo pip install -q behave
        - travis_retry sudo pip install -q colorama

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata behave --no-capture
        
after_failure:
        - cat $SONARHOME/logs/sonar.log
        - find . -name "*.log" | xargs cat
