version: '{build}'
environment:
  token:
    secure: P6Cj7IcyyNJPTG/5q2W1U4qXhRUQX8BazLcSh9Le8+Czfgmo/F/1VqY1HaMHZddu
  githubtoken:
    secure: f72Bkv7Kb0xkwE+CXE9BH9aV8iRIilNM2XANDOffRPazDf0luuu4w2wSQNt+RRZl
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if ((Test-Path -Path "C:\maven" )) {
        Remove-Item -Recurse -Force "C:\maven"
      }
            
      (new-object System.Net.WebClient).DownloadFile(
        'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
        'C:\maven-bin.zip'
      )
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")

      if (!(Test-Path -Path "C:\sonar-scanner" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.8.zip',
          'C:\sonar-scanner-dist.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sonar-scanner-dist.zip", "C:\sonar-scanner")
      }
      if (!(Test-Path -Path "C:\sonarqube" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.6.6.zip',
          'C:\sonarqube-5.6.6.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sonarqube-5.6.6.zip", "C:\sonarqube")
      }
  - ps: |
      If ($env:Platform -Match "x86") {
        $env:PCRE_PLATFORM="Win32"
        $env:JAVA_HOME="c:/Program Files (x86)/Java/jdk1.8.0"
        $env:MSBuildDir="C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe"
        $env:VCVARS_PLATFORM="x86"
        $env:LANG_PLATFORM=""
      } Else {
        $env:PCRE_PLATFORM="x64"
        $env:JAVA_HOME="c:/Program Files/Java/jdk1.8.0"
        $env:MSBuildDir="C:/Program Files/MSBuild/14.0/Bin/msbuild.exe"
        $env:VCVARS_PLATFORM="amd64"
        $env:LANG_PLATFORM="-x64"
      }
  - cmd: SET    
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;C:\sonar-scanner\sonar-scanner-2.8\bin;%PATH%
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET MAVEN_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET SONARHOME=C:\sonarqube\sonarqube-5.6.6
  - cmd: SET TestDataFolder=C:\projects\sonar-cxx\integration-tests\testdata
  - cmd: SET

build_script:
  - dir
  - echo on
  - echo %APPVEYOR_PULL_REQUEST_NUMBER%
  # SONAR-7154 : workaround
  - mkdir C:\WINDOWS\system32\config\systemprofile\AppData\Local\Temp
  - cd C:\WINDOWS\system32\config\systemprofile\AppData\Local\
  - dir
  - cd C:\projects\sonar-cxx
  - dir
  - C:\Python27\Scripts\pip.exe install requests
  - C:\Python27\Scripts\pip.exe install behave
  - C:\Python27\Scripts\pip.exe install colorama
  - mvn clean install
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%"==""  (sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.analysis.mode=preview -Dsonar.github.pullRequest=%APPVEYOR_PULL_REQUEST_NUMBER% -Dsonar.github.repository=SonarOpenCommunity/sonar-cxx -Dsonar.github.oauth=%githubtoken% -Dsonar.language=java -Dsonar.projectKey=sonar-cxx -Dsonar.projectName=sonar-cxx -Dsonar.login=%token% -Dsonar.sources=.) ELSE (ECHO SKIP ANALYSIS)
  - C:\Python27\Scripts\behave.exe --no-capture --tags=SqApi56
cache:
  - C:\Users\appveyor\.m2
artifacts:
  - path: 'sonar-cxx-plugin\target\*.jar'
  - path: 'sonar-c-plugin\target\*.jar'
  - path: 'sslr-cxx-toolkit\target\*.jar'
on_failure:
  - ps: Get-ChildItem cxx-squid\target\surefire-reports\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem cxx-checks\target\surefire-reports\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem sonar-cxx-plugin\target\surefire-reports\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem *.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem C:\sonarqube\sonarqube-5.6.6\logs\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }